"""
Healthcare AI Router — Monitoring Schema
=========================================
Pydantic schema for the execution telemetry record produced by
the Monitoring Node after every LangGraph execution.

Every field in ``MonitoringLog`` is stored as a document in the
MongoDB ``monitoring_logs`` collection and forwarded to LangSmith.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


class MonitoringLog(BaseModel):
    """
    Complete execution telemetry for a single LangGraph invocation.

    Attributes:
        correlation_id:     Unique request identifier.
        session_id:         Conversation session identifier.
        timestamp:          UTC time when the monitoring log was created.
        selected_agent:     Name of the specialized agent that handled the request.
        intent:             Classified intent from the Router Node.
        latency_ms:         Wall-clock duration from graph invocation to completion.
        execution_time_ms:  Same as latency_ms (alias for API clarity).
        prompt_tokens:      Tokens consumed by the LLM prompt.
        completion_tokens:  Tokens generated by the LLM completion.
        total_tokens:       Total tokens used in this invocation.
        status:             ``"success"`` or ``"error"``.
        error:              Error message if ``status == "error"``, else ``None``.
    """

    correlation_id: str = Field(..., description="Request correlation UUID")
    session_id: str = Field(..., description="Conversation session UUID")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="UTC timestamp of log creation",
    )
    selected_agent: str = Field(..., description="Agent that handled the request")
    intent: str = Field(..., description="Classified intent")
    latency_ms: float = Field(..., ge=0.0, description="End-to-end latency in ms")
    execution_time_ms: float = Field(
        ..., ge=0.0, description="Graph execution time in ms"
    )
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    status: Literal["success", "error"] = Field(..., description="Execution outcome")
    error: str | None = Field(default=None, description="Error details if status=error")

    model_config = {"json_encoders": {datetime: lambda v: v.isoformat()}}

    def to_mongo_doc(self) -> dict:
        """Serialise to a MongoDB-ready dict with ISO-formatted timestamps."""
        return self.model_dump(mode="json")
